version: '3.8'
services:
    updatecerts:
        image: vjedev/certupdater:latest
        volumes:
            - certs:/certs
    landingpage:
        image: vjedev/landingpage:latest
        volumes:
            - ./websites:/websites
    databaseimportexport:
        image: vjedev/database-import-export:latest
        volumes:
            - ./websites:/websites
        links:
            - mysql
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - certs:/certs
            - ./websites:/websites
        links:
            - php
        depends_on:
            - updatecerts
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./websites:/websites
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'student'
            MYSQL_USER: 'student'
            MYSQL_PASSWORD: 'student'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306                   
volumes:
    mysqldata: {}
    certs: {}