version: "3.8"
services:
  updatecerts:
    image: vjedev/certupdater:latest
    restart: on-failure
    volumes:
      - certs:/certs
      - mysqlconf:/mysqlconf
  landingpage:
    image: vjedev/landingpage:latest
    volumes:
      - ./websites:/websites
  databaseimportexport:
    image: vjedev/database-import-export:latest
    restart: on-failure
    volumes:
      - ./websites:/websites
    depends_on:
      - mysql
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - certs:/certs
      - ./websites:/websites
    depends_on:
      - updatecerts
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    restart: always
    volumes:
      - ./websites:/websites
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "v.je"
      MYSQL_USER: "v.je"
      MYSQL_PASSWORD: "v.je"
    volumes:
      - mysqldata:/var/lib/mysql
      - certs:/ssl
      - mysqlconf:/etc/mysql/conf.d/
    ports:
      - 3306:3306

volumes:
  mysqldata: {}
  certs: {}
  mysqlconf: {}
